// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // The CLI (migrate/db push) needs session-level features - advisory
  // locks, DDL - that the transaction-mode pooler in DATABASE_URL doesn't
  // support, so it uses the direct/session connection instead.
  datasource: {
    url: env("DIRECT_URL"),
  },
});
