import Link from "next/link";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Privacy Policy",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="flex flex-col">
      {/* Hero */}
      <section>
        <div className="max-w-4xl mx-auto w-full px-8 pt-20 pb-12 flex flex-col gap-4">
          <p className="text-sm font-medium text-brand dark:text-blue-400">Legal</p>
          <h1 className="text-4xl sm:text-5xl font-semibold">Privacy Policy</h1>
          <p className="text-lg text-black/60 dark:text-white/60 max-w-prose">
            AKUEB Prep is a free, student-built practice site and is not an official AKU-EB
            service. This page explains what information we collect and how we use it.
          </p>
          <p className="text-sm text-black/40 dark:text-white/40">Last updated: 21 August 2026</p>
        </div>
      </section>

      {/* Content */}
      <section className="border-t border-black/10 dark:border-white/10">
        <div className="max-w-4xl mx-auto w-full px-8 py-16">
          <div className="prose-content text-black/80 dark:text-white/80">
            <h2>Who we are</h2>
            <p>
              AKUEB Prep (&ldquo;we&rdquo;, &ldquo;us&rdquo;) is an independent, free question
              bank for AKU-EB students, built and run by a single student developer. We are not
              affiliated with, endorsed by, or operated on behalf of the Aga Khan University
              Examination Board (AKU-EB).
            </p>

            <h2>Information we collect</h2>
            <p>When you use AKUEB Prep, we collect:</p>
            <ul>
              <li>
                <strong>Account information</strong> - your email address, and your name if you
                choose to provide one, either when you sign up with a password or when you sign
                in with Google. Passwords are handled by our authentication provider, Supabase,
                and are never stored or seen by us in plain text.
              </li>
              <li>
                <strong>Usage and progress data</strong> - which questions and past papers you&apos;ve
                solved, your answers, points earned, and test attempts, so we can show your
                progress and let you pick up where you left off.
              </li>
              <li>
                <strong>Technical data</strong> - standard server logs (such as IP address and
                browser type) generated by our hosting provider for security and reliability.
              </li>
            </ul>
            <p>
              We do not run advertising or third-party analytics/tracking scripts on AKUEB Prep,
              and we do not collect payment information - the site is free.
            </p>

            <h2>How we use this information</h2>
            <ul>
              <li>To create and manage your account and keep you signed in.</li>
              <li>To save and display your solved questions, points, and progress.</li>
              <li>To operate, maintain, and improve the site.</li>
              <li>To respond if you contact us with a question or a reported error.</li>
            </ul>
            <p>We do not sell your personal information, and we do not share it with advertisers.</p>

            <h2>Cookies</h2>
            <p>
              We use a small number of essential cookies set by our authentication provider,
              Supabase, to keep you signed in. These are required for the site to function and
              are not used for advertising or cross-site tracking.
            </p>

            <h2>Who we share data with</h2>
            <p>
              We use the following third-party service providers to run AKUEB Prep, each of which
              processes data on our behalf under their own security practices:
            </p>
            <ul>
              <li><strong>Supabase</strong> - authentication and session management.</li>
              <li><strong>Our database and hosting providers</strong> - to store account, progress, and question-bank data and serve the site.</li>
            </ul>
            <p>We do not otherwise share your personal data with third parties, except where required by law.</p>

            <h2>Data retention and deletion</h2>
            <p>
              We keep your account and progress data for as long as your account is active. You
              can request deletion of your account and associated data at any time by emailing{" "}
              <a href="mailto:akuebprep@gmail.com">akuebprep@gmail.com</a>; we&apos;ll action
              deletion requests within a reasonable time.
            </p>

            <h2>Security</h2>
            <p>
              We take reasonable steps to protect your information, including relying on
              Supabase for secure authentication. However, no online service can guarantee
              perfect security, and we cannot guarantee the absolute security of your data.
            </p>

            <h2>Children&apos;s privacy</h2>
            <p>
              AKUEB Prep is intended for AKU-EB students, some of whom may be under 18. We only
              collect the information described above, do not knowingly collect more than is
              necessary to operate the site, and do not use it for advertising. If you are a
              parent or guardian with concerns about a minor&apos;s account, contact us and we&apos;ll
              help.
            </p>

            <h2>Changes to this policy</h2>
            <p>
              We may update this policy as the site changes. If we make significant changes,
              we&apos;ll update the &ldquo;Last updated&rdquo; date above.
            </p>

            <h2>Contact us</h2>
            <p>
              Questions about this policy or your data? Email{" "}
              <a href="mailto:akuebprep@gmail.com">akuebprep@gmail.com</a>. See also our{" "}
              <Link href="/terms-of-service">Terms of Service</Link> and{" "}
              <Link href="/about">About</Link> page.
            </p>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
